### ISSUE TITLE
adding doors from ymap

### ISSUE THREAD

**Issue by vinookie** [BulgaRpl/bulgar_doorlocks_vorp#5]
Hi there, is it possible to make custom spawned doors open/closable?
I made a ymap with map editor, loaded the files in stream.
I looked up for the native hash https://github.com/femga/rdr3_discoveries/blob/master/doorHashes/doorhashes.lua , the icon will be displayed and iam able to press alt, but the door does not close.

**Comment by BulgaRpl** [comment]
Try to use the plugin "PROPGUN" or similar to find the right door ID. "doorhashes.lua" is for existing doors in game not the ymap ones.
